"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import LiveIndicator from "@/components/ui/LiveIndicator";

interface Counter { id:string; name:string; location:string|null; status:"OPEN"|"CLOSED"|"PAUSED" }
interface Token { id:string; token_number:string; status:string; created_at:string; called_at:string|null; service_started_at:string|null; arrived_at:string|null; services:{name:string}|null }
interface Props { counter:Counter }
const NO_SHOW_SECONDS=5*60;

export default function StaffQueue({counter}:Props){
 const supabase=createClient(); const [counterStatus,setCounterStatus]=useState(counter.status); const [tokens,setTokens]=useState<Token[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [now,setNow]=useState(()=>Date.now());
 const loadQueue=async()=>{const {data,error}=await supabase.from("tokens").select(`id,token_number,status,created_at,called_at,service_started_at,arrived_at,services(name)`).eq("counter_id",counter.id).in("status",["WAITING","CALLED","IN_SERVICE"]).order("created_at",{ascending:true}); if(error){setError(error.message);return;} setTokens((data as Token[])??[])};
 useEffect(()=>{loadQueue();const channel=supabase.channel(`counter-${counter.id}`).on("postgres_changes",{event:"*",schema:"public",table:"tokens",filter:`counter_id=eq.${counter.id}`},()=>loadQueue()).on("postgres_changes",{event:"*",schema:"public",table:"counters",filter:`id=eq.${counter.id}`},payload=>{const status=(payload.new as {status?:Counter["status"]})?.status;if(status)setCounterStatus(status)}).subscribe();return()=>{supabase.removeChannel(channel)}},[counter.id,supabase]);
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{if(counterStatus!=="OPEN")return;const expire=async()=>{const {error}=await supabase.rpc("expire_no_show_tokens",{p_counter_id:counter.id});if(!error)await loadQueue()};expire();const timer=window.setInterval(expire,15000);return()=>window.clearInterval(timer)},[counter.id,counterStatus,supabase]);
 async function runAction(action:()=>Promise<{error:any}>){setLoading(true);setError("");const {error}=await action();if(error)setError(error.message);await loadQueue();setLoading(false)}
 async function openCounter(){await runAction(async()=>{const result=await supabase.rpc("open_counter",{p_counter_id:counter.id});if(!result.error)setCounterStatus("OPEN");return result})}
 async function closeCounter(){await runAction(async()=>{const result=await supabase.rpc("close_counter",{p_counter_id:counter.id,p_reason:"Closed by staff"});if(!result.error)setCounterStatus("CLOSED");return result})}
 async function callNext(){await runAction(()=>supabase.rpc("call_next_token",{p_counter_id:counter.id}))}
 async function checkIn(tokenId:string){await runAction(()=>supabase.rpc("check_in_token",{p_token_id:tokenId}))}
 async function startService(tokenId:string){await runAction(()=>supabase.rpc("start_token_service",{p_token_id:tokenId}))}
 async function completeToken(tokenId:string){await runAction(()=>supabase.rpc("complete_token",{p_token_id:tokenId}))}
 async function skipToken(tokenId:string){await runAction(()=>supabase.rpc("skip_token",{p_token_id:tokenId}))}
 const currentToken=useMemo(()=>tokens.find(t=>["CALLED","IN_SERVICE"].includes(t.status)),[tokens]); const waitingTokens=useMemo(()=>tokens.filter(t=>t.status==="WAITING"),[tokens]);
 const calledElapsedSeconds=currentToken?.called_at?Math.max(0,Math.floor((now-new Date(currentToken.called_at).getTime())/1000)):0; const remainingNoShowSeconds=Math.max(0,NO_SHOW_SECONDS-calledElapsedSeconds); const hasTimedOut=currentToken?.status==="CALLED"&&remainingNoShowSeconds===0;
 return <div className="overflow-hidden rounded-3xl border bg-white shadow-sm">
  <div className="border-b p-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-bold">{counter.name}</h3><p className="mt-1 text-sm text-slate-500">{counter.location}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${counterStatus==="OPEN"?"bg-green-50 text-green-700":counterStatus==="PAUSED"?"bg-yellow-50 text-yellow-700":"bg-slate-100 text-slate-500"}`}>{counterStatus}</span></div></div>
  <div className="p-6">
   {currentToken?<div><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-slate-500">NOW SERVING</p><LiveIndicator/></div><p className="mt-2 text-6xl font-black tracking-tight">{currentToken.token_number}</p><p className="mt-2 font-medium">{currentToken.services?.name}</p>
    {currentToken.status==="CALLED"&&<div className={`mt-5 rounded-2xl p-4 ${currentToken.arrived_at?"bg-green-50 text-green-800":hasTimedOut?"bg-red-50 text-red-800":"bg-yellow-50 text-yellow-800"}`}><div className="flex items-center justify-between gap-4"><div><p className="font-semibold">{currentToken.arrived_at?"Student has checked in":hasTimedOut?"No-show threshold reached":"Waiting for student arrival"}</p><p className="mt-1 text-sm opacity-80">Called {formatDuration(calledElapsedSeconds)} ago</p></div><div className="text-right"><p className="text-xs font-medium uppercase tracking-wide opacity-70">{currentToken.arrived_at?"Checked in":"Auto-skip in"}</p><p className="mt-1 text-2xl font-black">{currentToken.arrived_at?"✓":formatDuration(remainingNoShowSeconds)}</p></div></div></div>}
    {currentToken.status==="IN_SERVICE"&&<div className="mt-5 rounded-2xl bg-blue-50 p-4 text-blue-800"><p className="font-semibold">Service in progress</p><p className="mt-1 text-sm opacity-80">The student is currently being served.</p></div>}
    <div className="mt-5 flex gap-3">{currentToken.status==="CALLED"&&!currentToken.arrived_at&&!hasTimedOut&&<button onClick={()=>checkIn(currentToken.id)} disabled={loading} className="flex-1 rounded-xl bg-green-600 px-4 py-3 font-semibold text-white disabled:opacity-40">✓ Check In Student</button>}{currentToken.status==="CALLED"&&currentToken.arrived_at&&<button onClick={()=>startService(currentToken.id)} disabled={loading} className="flex-1 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-40">Start Service</button>}{currentToken.status==="CALLED"&&!currentToken.arrived_at&&<button disabled className="flex-1 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white opacity-40">Waiting for Arrival</button>}{currentToken.status==="IN_SERVICE"&&<button onClick={()=>completeToken(currentToken.id)} disabled={loading} className="flex-1 rounded-xl bg-green-600 px-4 py-3 font-semibold text-white disabled:opacity-40">Complete Service</button>}<button onClick={()=>skipToken(currentToken.id)} disabled={loading} className="rounded-xl border px-4 py-3 font-semibold disabled:opacity-40">Skip</button></div>
   </div>:<div className="rounded-2xl bg-slate-50 p-6 text-center"><p className="text-sm text-slate-500">No student currently being served</p><p className="mt-2 text-4xl font-bold">—</p></div>}
   <div className="mt-8 border-t pt-6"><div className="flex items-center justify-between gap-4"><div><h4 className="font-semibold">Waiting Queue</h4><p className="mt-1 text-xs text-slate-400">Tokens are ordered by arrival time.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-600">{waitingTokens.length} waiting</span></div><div className="mt-4 space-y-2">{waitingTokens.map((token,index)=><div key={token.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-white text-xs font-bold text-slate-500">{index+1}</span><div><p className="font-semibold">{token.token_number}</p><p className="text-xs text-slate-400">Waiting</p></div></div><span className="text-sm text-slate-500">{token.services?.name}</span></div>)}{waitingTokens.length===0&&<p className="py-4 text-center text-sm text-slate-400">No students waiting</p>}</div></div>
   <div className="mt-6 flex gap-3">{counterStatus==="OPEN"?<><button onClick={callNext} disabled={loading||waitingTokens.length===0||!!currentToken} className="flex-1 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Call Next</button><button onClick={closeCounter} disabled={loading||!!currentToken} className="rounded-xl border px-4 py-3 font-semibold disabled:cursor-not-allowed disabled:opacity-40">Close</button></>:<button onClick={openCounter} disabled={loading} className="w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-40">Open Counter</button>}</div>
   {counterStatus==="OPEN"&&waitingTokens.length===0&&!currentToken&&<div className="mt-4 rounded-xl bg-green-50 p-3 text-center text-sm font-medium text-green-700">Counter is open and the queue is clear.</div>}{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</div>}
  </div>
 </div>
}
function formatDuration(totalSeconds:number){const minutes=Math.floor(totalSeconds/60);const seconds=totalSeconds%60;return `${minutes}:${seconds.toString().padStart(2,"0")}`}
